// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: badminton/analysis/v1/analysis.proto

package analysisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BadmintonAnalysis_AnalyzeVideo_FullMethodName        = "/badminton.analysis.v1.BadmintonAnalysis/AnalyzeVideo"
	BadmintonAnalysis_RefreshPlaybackUrls_FullMethodName = "/badminton.analysis.v1.BadmintonAnalysis/RefreshPlaybackUrls"
	BadmintonAnalysis_Health_FullMethodName              = "/badminton.analysis.v1.BadmintonAnalysis/Health"
)

// BadmintonAnalysisClient is the client API for BadmintonAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BadmintonAnalysisClient interface {
	AnalyzeVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AnalyzeVideoChunk, AnalyzeVideoResponse], error)
	RefreshPlaybackUrls(ctx context.Context, in *RefreshPlaybackUrlsRequest, opts ...grpc.CallOption) (*RefreshPlaybackUrlsResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type badmintonAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewBadmintonAnalysisClient(cc grpc.ClientConnInterface) BadmintonAnalysisClient {
	return &badmintonAnalysisClient{cc}
}

func (c *badmintonAnalysisClient) AnalyzeVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AnalyzeVideoChunk, AnalyzeVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BadmintonAnalysis_ServiceDesc.Streams[0], BadmintonAnalysis_AnalyzeVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeVideoChunk, AnalyzeVideoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BadmintonAnalysis_AnalyzeVideoClient = grpc.ClientStreamingClient[AnalyzeVideoChunk, AnalyzeVideoResponse]

func (c *badmintonAnalysisClient) RefreshPlaybackUrls(ctx context.Context, in *RefreshPlaybackUrlsRequest, opts ...grpc.CallOption) (*RefreshPlaybackUrlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshPlaybackUrlsResponse)
	err := c.cc.Invoke(ctx, BadmintonAnalysis_RefreshPlaybackUrls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badmintonAnalysisClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BadmintonAnalysis_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadmintonAnalysisServer is the server API for BadmintonAnalysis service.
// All implementations must embed UnimplementedBadmintonAnalysisServer
// for forward compatibility.
type BadmintonAnalysisServer interface {
	AnalyzeVideo(grpc.ClientStreamingServer[AnalyzeVideoChunk, AnalyzeVideoResponse]) error
	RefreshPlaybackUrls(context.Context, *RefreshPlaybackUrlsRequest) (*RefreshPlaybackUrlsResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBadmintonAnalysisServer()
}

// UnimplementedBadmintonAnalysisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadmintonAnalysisServer struct{}

func (UnimplementedBadmintonAnalysisServer) AnalyzeVideo(grpc.ClientStreamingServer[AnalyzeVideoChunk, AnalyzeVideoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AnalyzeVideo not implemented")
}
func (UnimplementedBadmintonAnalysisServer) RefreshPlaybackUrls(context.Context, *RefreshPlaybackUrlsRequest) (*RefreshPlaybackUrlsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshPlaybackUrls not implemented")
}
func (UnimplementedBadmintonAnalysisServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBadmintonAnalysisServer) mustEmbedUnimplementedBadmintonAnalysisServer() {}
func (UnimplementedBadmintonAnalysisServer) testEmbeddedByValue()                           {}

// UnsafeBadmintonAnalysisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadmintonAnalysisServer will
// result in compilation errors.
type UnsafeBadmintonAnalysisServer interface {
	mustEmbedUnimplementedBadmintonAnalysisServer()
}

func RegisterBadmintonAnalysisServer(s grpc.ServiceRegistrar, srv BadmintonAnalysisServer) {
	// If the following call pancis, it indicates UnimplementedBadmintonAnalysisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadmintonAnalysis_ServiceDesc, srv)
}

func _BadmintonAnalysis_AnalyzeVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BadmintonAnalysisServer).AnalyzeVideo(&grpc.GenericServerStream[AnalyzeVideoChunk, AnalyzeVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BadmintonAnalysis_AnalyzeVideoServer = grpc.ClientStreamingServer[AnalyzeVideoChunk, AnalyzeVideoResponse]

func _BadmintonAnalysis_RefreshPlaybackUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshPlaybackUrlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadmintonAnalysisServer).RefreshPlaybackUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadmintonAnalysis_RefreshPlaybackUrls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadmintonAnalysisServer).RefreshPlaybackUrls(ctx, req.(*RefreshPlaybackUrlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadmintonAnalysis_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadmintonAnalysisServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadmintonAnalysis_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadmintonAnalysisServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadmintonAnalysis_ServiceDesc is the grpc.ServiceDesc for BadmintonAnalysis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadmintonAnalysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "badminton.analysis.v1.BadmintonAnalysis",
	HandlerType: (*BadmintonAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshPlaybackUrls",
			Handler:    _BadmintonAnalysis_RefreshPlaybackUrls_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BadmintonAnalysis_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeVideo",
			Handler:       _BadmintonAnalysis_AnalyzeVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "badminton/analysis/v1/analysis.proto",
}
