// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: badminton/analysis/v1/analysis.proto

package analysisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill int32

const (
	Skill_SKILL_UNSPECIFIED Skill = 0
	Skill_SKILL_SERVE       Skill = 1
	Skill_SKILL_LIFT        Skill = 2
	Skill_SKILL_CLEAR       Skill = 3
	Skill_SKILL_SMASH       Skill = 4
)

// Enum value maps for Skill.
var (
	Skill_name = map[int32]string{
		0: "SKILL_UNSPECIFIED",
		1: "SKILL_SERVE",
		2: "SKILL_LIFT",
		3: "SKILL_CLEAR",
		4: "SKILL_SMASH",
	}
	Skill_value = map[string]int32{
		"SKILL_UNSPECIFIED": 0,
		"SKILL_SERVE":       1,
		"SKILL_LIFT":        2,
		"SKILL_CLEAR":       3,
		"SKILL_SMASH":       4,
	}
)

func (x Skill) Enum() *Skill {
	p := new(Skill)
	*p = x
	return p
}

func (x Skill) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Skill) Descriptor() protoreflect.EnumDescriptor {
	return file_badminton_analysis_v1_analysis_proto_enumTypes[0].Descriptor()
}

func (Skill) Type() protoreflect.EnumType {
	return &file_badminton_analysis_v1_analysis_proto_enumTypes[0]
}

func (x Skill) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Skill.Descriptor instead.
func (Skill) EnumDescriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{0}
}

type Handedness int32

const (
	Handedness_HANDEDNESS_UNSPECIFIED Handedness = 0
	Handedness_HANDEDNESS_AUTO        Handedness = 1
	Handedness_HANDEDNESS_RIGHT       Handedness = 2
	Handedness_HANDEDNESS_LEFT        Handedness = 3
)

// Enum value maps for Handedness.
var (
	Handedness_name = map[int32]string{
		0: "HANDEDNESS_UNSPECIFIED",
		1: "HANDEDNESS_AUTO",
		2: "HANDEDNESS_RIGHT",
		3: "HANDEDNESS_LEFT",
	}
	Handedness_value = map[string]int32{
		"HANDEDNESS_UNSPECIFIED": 0,
		"HANDEDNESS_AUTO":        1,
		"HANDEDNESS_RIGHT":       2,
		"HANDEDNESS_LEFT":        3,
	}
)

func (x Handedness) Enum() *Handedness {
	p := new(Handedness)
	*p = x
	return p
}

func (x Handedness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Handedness) Descriptor() protoreflect.EnumDescriptor {
	return file_badminton_analysis_v1_analysis_proto_enumTypes[1].Descriptor()
}

func (Handedness) Type() protoreflect.EnumType {
	return &file_badminton_analysis_v1_analysis_proto_enumTypes[1]
}

func (x Handedness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Handedness.Descriptor instead.
func (Handedness) EnumDescriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{1}
}

type AnalyzeVideoHeader struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename   string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Skill      Skill                  `protobuf:"varint,4,opt,name=skill,proto3,enum=badminton.analysis.v1.Skill" json:"skill,omitempty"`
	Handedness Handedness             `protobuf:"varint,5,opt,name=handedness,proto3,enum=badminton.analysis.v1.Handedness" json:"handedness,omitempty"`
	// Skip the coaching pass entirely. Coaching is the only stage that leaves
	// this service: it sends sampled frames of the learner to a third-party
	// model. A deployment that has not obtained consent for that sets this, and
	// then no image of the learner goes anywhere. The analysis itself is
	// unaffected -- pose, correction, grading and expert matching are local --
	// so the response is the same minus coaching_cues and overall_feedback.
	SkipCoaching bool `protobuf:"varint,6,opt,name=skip_coaching,json=skipCoaching,proto3" json:"skip_coaching,omitempty"`
	// Top-level prefix for everything this analysis writes to storage. Several
	// deployments share this service and therefore share the bucket it writes
	// to, and they also share a LINE login channel, so learner ids do not tell
	// their recordings apart. The caller names itself here instead. Empty keeps
	// the historic unprefixed layout, which is what the original deployment
	// already has in the bucket.
	StoragePrefix string `protobuf:"bytes,7,opt,name=storage_prefix,json=storagePrefix,proto3" json:"storage_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoHeader) Reset() {
	*x = AnalyzeVideoHeader{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoHeader) ProtoMessage() {}

func (x *AnalyzeVideoHeader) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoHeader.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoHeader) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeVideoHeader) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeVideoHeader) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeVideoHeader) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzeVideoHeader) GetSkill() Skill {
	if x != nil {
		return x.Skill
	}
	return Skill_SKILL_UNSPECIFIED
}

func (x *AnalyzeVideoHeader) GetHandedness() Handedness {
	if x != nil {
		return x.Handedness
	}
	return Handedness_HANDEDNESS_UNSPECIFIED
}

func (x *AnalyzeVideoHeader) GetSkipCoaching() bool {
	if x != nil {
		return x.SkipCoaching
	}
	return false
}

func (x *AnalyzeVideoHeader) GetStoragePrefix() string {
	if x != nil {
		return x.StoragePrefix
	}
	return ""
}

type AnalyzeVideoChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AnalyzeVideoChunk_Header
	//	*AnalyzeVideoChunk_Data
	Payload       isAnalyzeVideoChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoChunk) Reset() {
	*x = AnalyzeVideoChunk{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoChunk) ProtoMessage() {}

func (x *AnalyzeVideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoChunk.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoChunk) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeVideoChunk) GetPayload() isAnalyzeVideoChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AnalyzeVideoChunk) GetHeader() *AnalyzeVideoHeader {
	if x != nil {
		if x, ok := x.Payload.(*AnalyzeVideoChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *AnalyzeVideoChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AnalyzeVideoChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isAnalyzeVideoChunk_Payload interface {
	isAnalyzeVideoChunk_Payload()
}

type AnalyzeVideoChunk_Header struct {
	Header *AnalyzeVideoHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type AnalyzeVideoChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*AnalyzeVideoChunk_Header) isAnalyzeVideoChunk_Payload() {}

func (*AnalyzeVideoChunk_Data) isAnalyzeVideoChunk_Payload() {}

type GradingDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriterionId   string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Grade         float64                `protobuf:"fixed64,3,opt,name=grade,proto3" json:"grade,omitempty"`
	Maximum       float64                `protobuf:"fixed64,4,opt,name=maximum,proto3" json:"maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradingDetail) Reset() {
	*x = GradingDetail{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradingDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradingDetail) ProtoMessage() {}

func (x *GradingDetail) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradingDetail.ProtoReflect.Descriptor instead.
func (*GradingDetail) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *GradingDetail) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *GradingDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GradingDetail) GetGrade() float64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *GradingDetail) GetMaximum() float64 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

type GradingOutcome struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalGrade     float64                `protobuf:"fixed64,1,opt,name=total_grade,json=totalGrade,proto3" json:"total_grade,omitempty"`
	GradingDetails []*GradingDetail       `protobuf:"bytes,2,rep,name=grading_details,json=gradingDetails,proto3" json:"grading_details,omitempty"`
	ScoreStatus    string                 `protobuf:"bytes,3,opt,name=score_status,json=scoreStatus,proto3" json:"score_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GradingOutcome) Reset() {
	*x = GradingOutcome{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradingOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradingOutcome) ProtoMessage() {}

func (x *GradingOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradingOutcome.ProtoReflect.Descriptor instead.
func (*GradingOutcome) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *GradingOutcome) GetTotalGrade() float64 {
	if x != nil {
		return x.TotalGrade
	}
	return 0
}

func (x *GradingOutcome) GetGradingDetails() []*GradingDetail {
	if x != nil {
		return x.GradingDetails
	}
	return nil
}

func (x *GradingOutcome) GetScoreStatus() string {
	if x != nil {
		return x.ScoreStatus
	}
	return ""
}

type PhaseMarker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label              string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	NormalizedFrame    int32                  `protobuf:"varint,3,opt,name=normalized_frame,json=normalizedFrame,proto3" json:"normalized_frame,omitempty"`
	NormalizedPosition float64                `protobuf:"fixed64,4,opt,name=normalized_position,json=normalizedPosition,proto3" json:"normalized_position,omitempty"`
	TimestampSeconds   float64                `protobuf:"fixed64,5,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PhaseMarker) Reset() {
	*x = PhaseMarker{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseMarker) ProtoMessage() {}

func (x *PhaseMarker) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseMarker.ProtoReflect.Descriptor instead.
func (*PhaseMarker) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *PhaseMarker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhaseMarker) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PhaseMarker) GetNormalizedFrame() int32 {
	if x != nil {
		return x.NormalizedFrame
	}
	return 0
}

func (x *PhaseMarker) GetNormalizedPosition() float64 {
	if x != nil {
		return x.NormalizedPosition
	}
	return 0
}

func (x *PhaseMarker) GetTimestampSeconds() float64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

// One point on the map from the learner's motion onto the expert's clock.
//
// The checkpoints in ExpertMatch.timeline are fixed anchors; these fill in the
// movement between them. Playback would otherwise interpolate straight from one
// checkpoint to the next, which assumes the two performers keep the same
// relative tempo inside a phase -- they do not.
type AlignmentSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the learner is in their motion, 0-1.
	NormalizedPosition float64 `protobuf:"fixed64,1,opt,name=normalized_position,json=normalizedPosition,proto3" json:"normalized_position,omitempty"`
	// The moment in the expert's video that matches it.
	ExpertSeconds float64 `protobuf:"fixed64,2,opt,name=expert_seconds,json=expertSeconds,proto3" json:"expert_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignmentSample) Reset() {
	*x = AlignmentSample{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignmentSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignmentSample) ProtoMessage() {}

func (x *AlignmentSample) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignmentSample.ProtoReflect.Descriptor instead.
func (*AlignmentSample) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *AlignmentSample) GetNormalizedPosition() float64 {
	if x != nil {
		return x.NormalizedPosition
	}
	return 0
}

func (x *AlignmentSample) GetExpertSeconds() float64 {
	if x != nil {
		return x.ExpertSeconds
	}
	return 0
}

type CoachingCue struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Title                   string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Feedback                string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	NormalizedFrame         int32                  `protobuf:"varint,3,opt,name=normalized_frame,json=normalizedFrame,proto3" json:"normalized_frame,omitempty"`
	NormalizedPosition      float64                `protobuf:"fixed64,4,opt,name=normalized_position,json=normalizedPosition,proto3" json:"normalized_position,omitempty"`
	StudentTimestampSeconds float64                `protobuf:"fixed64,5,opt,name=student_timestamp_seconds,json=studentTimestampSeconds,proto3" json:"student_timestamp_seconds,omitempty"`
	PauseDurationSeconds    float64                `protobuf:"fixed64,6,opt,name=pause_duration_seconds,json=pauseDurationSeconds,proto3" json:"pause_duration_seconds,omitempty"`
	JointIds                []int32                `protobuf:"varint,7,rep,packed,name=joint_ids,json=jointIds,proto3" json:"joint_ids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CoachingCue) Reset() {
	*x = CoachingCue{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoachingCue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoachingCue) ProtoMessage() {}

func (x *CoachingCue) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoachingCue.ProtoReflect.Descriptor instead.
func (*CoachingCue) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *CoachingCue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CoachingCue) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *CoachingCue) GetNormalizedFrame() int32 {
	if x != nil {
		return x.NormalizedFrame
	}
	return 0
}

func (x *CoachingCue) GetNormalizedPosition() float64 {
	if x != nil {
		return x.NormalizedPosition
	}
	return 0
}

func (x *CoachingCue) GetStudentTimestampSeconds() float64 {
	if x != nil {
		return x.StudentTimestampSeconds
	}
	return 0
}

func (x *CoachingCue) GetPauseDurationSeconds() float64 {
	if x != nil {
		return x.PauseDurationSeconds
	}
	return 0
}

func (x *CoachingCue) GetJointIds() []int32 {
	if x != nil {
		return x.JointIds
	}
	return nil
}

type StoredVideo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ObjectPath             string                 `protobuf:"bytes,1,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"`
	GcsUri                 string                 `protobuf:"bytes,2,opt,name=gcs_uri,json=gcsUri,proto3" json:"gcs_uri,omitempty"`
	SignedUrl              string                 `protobuf:"bytes,3,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	SignedUrlExpiresAtUnix int64                  `protobuf:"varint,4,opt,name=signed_url_expires_at_unix,json=signedUrlExpiresAtUnix,proto3" json:"signed_url_expires_at_unix,omitempty"`
	DurationSeconds        float64                `protobuf:"fixed64,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Fps                    float64                `protobuf:"fixed64,6,opt,name=fps,proto3" json:"fps,omitempty"`
	Width                  int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height                 int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoredVideo) Reset() {
	*x = StoredVideo{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredVideo) ProtoMessage() {}

func (x *StoredVideo) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredVideo.ProtoReflect.Descriptor instead.
func (*StoredVideo) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *StoredVideo) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *StoredVideo) GetGcsUri() string {
	if x != nil {
		return x.GcsUri
	}
	return ""
}

func (x *StoredVideo) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *StoredVideo) GetSignedUrlExpiresAtUnix() int64 {
	if x != nil {
		return x.SignedUrlExpiresAtUnix
	}
	return 0
}

func (x *StoredVideo) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StoredVideo) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *StoredVideo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StoredVideo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ExpertMatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExpertId           string                 `protobuf:"bytes,1,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	DisplayName        string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CorrectionDistance float64                `protobuf:"fixed64,3,opt,name=correction_distance,json=correctionDistance,proto3" json:"correction_distance,omitempty"`
	Video              *StoredVideo           `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	MotionStartSeconds float64                `protobuf:"fixed64,5,opt,name=motion_start_seconds,json=motionStartSeconds,proto3" json:"motion_start_seconds,omitempty"`
	MotionEndSeconds   float64                `protobuf:"fixed64,6,opt,name=motion_end_seconds,json=motionEndSeconds,proto3" json:"motion_end_seconds,omitempty"`
	// The expert's own checkpoints, one per student timeline marker and in the
	// same order, timestamped in the expert video. Playback interpolates between
	// them so each phase stays aligned instead of drifting across the motion.
	Timeline []*PhaseMarker `protobuf:"bytes,7,rep,name=timeline,proto3" json:"timeline,omitempty"`
	// Dense student-to-expert correspondence from phase-segmental DTW, with the
	// checkpoints above as fixed endpoints. Empty when it could not be computed,
	// and on analyses recorded before it shipped; playback falls back to
	// interpolating between the checkpoints.
	Alignment     []*AlignmentSample `protobuf:"bytes,8,rep,name=alignment,proto3" json:"alignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertMatch) Reset() {
	*x = ExpertMatch{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertMatch) ProtoMessage() {}

func (x *ExpertMatch) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertMatch.ProtoReflect.Descriptor instead.
func (*ExpertMatch) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *ExpertMatch) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *ExpertMatch) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ExpertMatch) GetCorrectionDistance() float64 {
	if x != nil {
		return x.CorrectionDistance
	}
	return 0
}

func (x *ExpertMatch) GetVideo() *StoredVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *ExpertMatch) GetMotionStartSeconds() float64 {
	if x != nil {
		return x.MotionStartSeconds
	}
	return 0
}

func (x *ExpertMatch) GetMotionEndSeconds() float64 {
	if x != nil {
		return x.MotionEndSeconds
	}
	return 0
}

func (x *ExpertMatch) GetTimeline() []*PhaseMarker {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *ExpertMatch) GetAlignment() []*AlignmentSample {
	if x != nil {
		return x.Alignment
	}
	return nil
}

type DiagnosticValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticValue) Reset() {
	*x = DiagnosticValue{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticValue) ProtoMessage() {}

func (x *DiagnosticValue) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticValue.ProtoReflect.Descriptor instead.
func (*DiagnosticValue) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *DiagnosticValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DiagnosticValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AnalyzeVideoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId      string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Skill           Skill                  `protobuf:"varint,2,opt,name=skill,proto3,enum=badminton.analysis.v1.Skill" json:"skill,omitempty"`
	Handedness      Handedness             `protobuf:"varint,3,opt,name=handedness,proto3,enum=badminton.analysis.v1.Handedness" json:"handedness,omitempty"`
	Grade           *GradingOutcome        `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"`
	StudentVideo    *StoredVideo           `protobuf:"bytes,5,opt,name=student_video,json=studentVideo,proto3" json:"student_video,omitempty"`
	Expert          *ExpertMatch           `protobuf:"bytes,6,opt,name=expert,proto3" json:"expert,omitempty"`
	Timeline        []*PhaseMarker         `protobuf:"bytes,7,rep,name=timeline,proto3" json:"timeline,omitempty"`
	Diagnostics     []*DiagnosticValue     `protobuf:"bytes,8,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	CoachingCues    []*CoachingCue         `protobuf:"bytes,9,rep,name=coaching_cues,json=coachingCues,proto3" json:"coaching_cues,omitempty"`
	OverallFeedback string                 `protobuf:"bytes,10,opt,name=overall_feedback,json=overallFeedback,proto3" json:"overall_feedback,omitempty"`
	// Clean detected/corrected skeletons over the source video, without GPT
	// annotations or inserted coaching pauses.
	SkeletonOverlayVideo *StoredVideo `protobuf:"bytes,11,opt,name=skeleton_overlay_video,json=skeletonOverlayVideo,proto3" json:"skeleton_overlay_video,omitempty"`
	// GPT suggestions, circled joints, and coaching pauses. student_video is a
	// backward-compatible alias of this field.
	FeedbackVideo *StoredVideo `protobuf:"bytes,12,opt,name=feedback_video,json=feedbackVideo,proto3" json:"feedback_video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoResponse) Reset() {
	*x = AnalyzeVideoResponse{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoResponse) ProtoMessage() {}

func (x *AnalyzeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoResponse) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeVideoResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalyzeVideoResponse) GetSkill() Skill {
	if x != nil {
		return x.Skill
	}
	return Skill_SKILL_UNSPECIFIED
}

func (x *AnalyzeVideoResponse) GetHandedness() Handedness {
	if x != nil {
		return x.Handedness
	}
	return Handedness_HANDEDNESS_UNSPECIFIED
}

func (x *AnalyzeVideoResponse) GetGrade() *GradingOutcome {
	if x != nil {
		return x.Grade
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetStudentVideo() *StoredVideo {
	if x != nil {
		return x.StudentVideo
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetExpert() *ExpertMatch {
	if x != nil {
		return x.Expert
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetTimeline() []*PhaseMarker {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetDiagnostics() []*DiagnosticValue {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetCoachingCues() []*CoachingCue {
	if x != nil {
		return x.CoachingCues
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetOverallFeedback() string {
	if x != nil {
		return x.OverallFeedback
	}
	return ""
}

func (x *AnalyzeVideoResponse) GetSkeletonOverlayVideo() *StoredVideo {
	if x != nil {
		return x.SkeletonOverlayVideo
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetFeedbackVideo() *StoredVideo {
	if x != nil {
		return x.FeedbackVideo
	}
	return nil
}

type RefreshPlaybackUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectPaths   []string               `protobuf:"bytes,1,rep,name=object_paths,json=objectPaths,proto3" json:"object_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPlaybackUrlsRequest) Reset() {
	*x = RefreshPlaybackUrlsRequest{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPlaybackUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPlaybackUrlsRequest) ProtoMessage() {}

func (x *RefreshPlaybackUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPlaybackUrlsRequest.ProtoReflect.Descriptor instead.
func (*RefreshPlaybackUrlsRequest) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshPlaybackUrlsRequest) GetObjectPaths() []string {
	if x != nil {
		return x.ObjectPaths
	}
	return nil
}

type RefreshPlaybackUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*StoredVideo         `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPlaybackUrlsResponse) Reset() {
	*x = RefreshPlaybackUrlsResponse{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPlaybackUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPlaybackUrlsResponse) ProtoMessage() {}

func (x *RefreshPlaybackUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPlaybackUrlsResponse.ProtoReflect.Descriptor instead.
func (*RefreshPlaybackUrlsResponse) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshPlaybackUrlsResponse) GetVideos() []*StoredVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LoadedSkills  []Skill                `protobuf:"varint,2,rep,packed,name=loaded_skills,json=loadedSkills,proto3,enum=badminton.analysis.v1.Skill" json:"loaded_skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badminton_analysis_v1_analysis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_badminton_analysis_v1_analysis_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetLoadedSkills() []Skill {
	if x != nil {
		return x.LoadedSkills
	}
	return nil
}

var File_badminton_analysis_v1_analysis_proto protoreflect.FileDescriptor

const file_badminton_analysis_v1_analysis_proto_rawDesc = "" +
	"\n" +
	"$badminton/analysis/v1/analysis.proto\x12\x15badminton.analysis.v1\"\xab\x02\n" +
	"\x12AnalyzeVideoHeader\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x122\n" +
	"\x05skill\x18\x04 \x01(\x0e2\x1c.badminton.analysis.v1.SkillR\x05skill\x12A\n" +
	"\n" +
	"handedness\x18\x05 \x01(\x0e2!.badminton.analysis.v1.HandednessR\n" +
	"handedness\x12#\n" +
	"\rskip_coaching\x18\x06 \x01(\bR\fskipCoaching\x12%\n" +
	"\x0estorage_prefix\x18\a \x01(\tR\rstoragePrefix\"y\n" +
	"\x11AnalyzeVideoChunk\x12C\n" +
	"\x06header\x18\x01 \x01(\v2).badminton.analysis.v1.AnalyzeVideoHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x84\x01\n" +
	"\rGradingDetail\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x01R\x05grade\x12\x18\n" +
	"\amaximum\x18\x04 \x01(\x01R\amaximum\"\xa3\x01\n" +
	"\x0eGradingOutcome\x12\x1f\n" +
	"\vtotal_grade\x18\x01 \x01(\x01R\n" +
	"totalGrade\x12M\n" +
	"\x0fgrading_details\x18\x02 \x03(\v2$.badminton.analysis.v1.GradingDetailR\x0egradingDetails\x12!\n" +
	"\fscore_status\x18\x03 \x01(\tR\vscoreStatus\"\xbc\x01\n" +
	"\vPhaseMarker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12)\n" +
	"\x10normalized_frame\x18\x03 \x01(\x05R\x0fnormalizedFrame\x12/\n" +
	"\x13normalized_position\x18\x04 \x01(\x01R\x12normalizedPosition\x12+\n" +
	"\x11timestamp_seconds\x18\x05 \x01(\x01R\x10timestampSeconds\"i\n" +
	"\x0fAlignmentSample\x12/\n" +
	"\x13normalized_position\x18\x01 \x01(\x01R\x12normalizedPosition\x12%\n" +
	"\x0eexpert_seconds\x18\x02 \x01(\x01R\rexpertSeconds\"\xaa\x02\n" +
	"\vCoachingCue\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x12)\n" +
	"\x10normalized_frame\x18\x03 \x01(\x05R\x0fnormalizedFrame\x12/\n" +
	"\x13normalized_position\x18\x04 \x01(\x01R\x12normalizedPosition\x12:\n" +
	"\x19student_timestamp_seconds\x18\x05 \x01(\x01R\x17studentTimestampSeconds\x124\n" +
	"\x16pause_duration_seconds\x18\x06 \x01(\x01R\x14pauseDurationSeconds\x12\x1b\n" +
	"\tjoint_ids\x18\a \x03(\x05R\bjointIds\"\x8d\x02\n" +
	"\vStoredVideo\x12\x1f\n" +
	"\vobject_path\x18\x01 \x01(\tR\n" +
	"objectPath\x12\x17\n" +
	"\agcs_uri\x18\x02 \x01(\tR\x06gcsUri\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x03 \x01(\tR\tsignedUrl\x12:\n" +
	"\x1asigned_url_expires_at_unix\x18\x04 \x01(\x03R\x16signedUrlExpiresAtUnix\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x01R\x0fdurationSeconds\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\x01R\x03fps\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\"\x9e\x03\n" +
	"\vExpertMatch\x12\x1b\n" +
	"\texpert_id\x18\x01 \x01(\tR\bexpertId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12/\n" +
	"\x13correction_distance\x18\x03 \x01(\x01R\x12correctionDistance\x128\n" +
	"\x05video\x18\x04 \x01(\v2\".badminton.analysis.v1.StoredVideoR\x05video\x120\n" +
	"\x14motion_start_seconds\x18\x05 \x01(\x01R\x12motionStartSeconds\x12,\n" +
	"\x12motion_end_seconds\x18\x06 \x01(\x01R\x10motionEndSeconds\x12>\n" +
	"\btimeline\x18\a \x03(\v2\".badminton.analysis.v1.PhaseMarkerR\btimeline\x12D\n" +
	"\talignment\x18\b \x03(\v2&.badminton.analysis.v1.AlignmentSampleR\talignment\"9\n" +
	"\x0fDiagnosticValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x93\x06\n" +
	"\x14AnalyzeVideoResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x122\n" +
	"\x05skill\x18\x02 \x01(\x0e2\x1c.badminton.analysis.v1.SkillR\x05skill\x12A\n" +
	"\n" +
	"handedness\x18\x03 \x01(\x0e2!.badminton.analysis.v1.HandednessR\n" +
	"handedness\x12;\n" +
	"\x05grade\x18\x04 \x01(\v2%.badminton.analysis.v1.GradingOutcomeR\x05grade\x12G\n" +
	"\rstudent_video\x18\x05 \x01(\v2\".badminton.analysis.v1.StoredVideoR\fstudentVideo\x12:\n" +
	"\x06expert\x18\x06 \x01(\v2\".badminton.analysis.v1.ExpertMatchR\x06expert\x12>\n" +
	"\btimeline\x18\a \x03(\v2\".badminton.analysis.v1.PhaseMarkerR\btimeline\x12H\n" +
	"\vdiagnostics\x18\b \x03(\v2&.badminton.analysis.v1.DiagnosticValueR\vdiagnostics\x12G\n" +
	"\rcoaching_cues\x18\t \x03(\v2\".badminton.analysis.v1.CoachingCueR\fcoachingCues\x12)\n" +
	"\x10overall_feedback\x18\n" +
	" \x01(\tR\x0foverallFeedback\x12X\n" +
	"\x16skeleton_overlay_video\x18\v \x01(\v2\".badminton.analysis.v1.StoredVideoR\x14skeletonOverlayVideo\x12I\n" +
	"\x0efeedback_video\x18\f \x01(\v2\".badminton.analysis.v1.StoredVideoR\rfeedbackVideo\"?\n" +
	"\x1aRefreshPlaybackUrlsRequest\x12!\n" +
	"\fobject_paths\x18\x01 \x03(\tR\vobjectPaths\"Y\n" +
	"\x1bRefreshPlaybackUrlsResponse\x12:\n" +
	"\x06videos\x18\x01 \x03(\v2\".badminton.analysis.v1.StoredVideoR\x06videos\"\x0f\n" +
	"\rHealthRequest\"k\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12A\n" +
	"\rloaded_skills\x18\x02 \x03(\x0e2\x1c.badminton.analysis.v1.SkillR\floadedSkills*a\n" +
	"\x05Skill\x12\x15\n" +
	"\x11SKILL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSKILL_SERVE\x10\x01\x12\x0e\n" +
	"\n" +
	"SKILL_LIFT\x10\x02\x12\x0f\n" +
	"\vSKILL_CLEAR\x10\x03\x12\x0f\n" +
	"\vSKILL_SMASH\x10\x04*h\n" +
	"\n" +
	"Handedness\x12\x1a\n" +
	"\x16HANDEDNESS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHANDEDNESS_AUTO\x10\x01\x12\x14\n" +
	"\x10HANDEDNESS_RIGHT\x10\x02\x12\x13\n" +
	"\x0fHANDEDNESS_LEFT\x10\x032\xd1\x02\n" +
	"\x11BadmintonAnalysis\x12g\n" +
	"\fAnalyzeVideo\x12(.badminton.analysis.v1.AnalyzeVideoChunk\x1a+.badminton.analysis.v1.AnalyzeVideoResponse(\x01\x12|\n" +
	"\x13RefreshPlaybackUrls\x121.badminton.analysis.v1.RefreshPlaybackUrlsRequest\x1a2.badminton.analysis.v1.RefreshPlaybackUrlsResponse\x12U\n" +
	"\x06Health\x12$.badminton.analysis.v1.HealthRequest\x1a%.badminton.analysis.v1.HealthResponseBBZ@github.com/HeavenAQ/nstc-linebot-2025/api/analysis/v1;analysisv1b\x06proto3"

var (
	file_badminton_analysis_v1_analysis_proto_rawDescOnce sync.Once
	file_badminton_analysis_v1_analysis_proto_rawDescData []byte
)

func file_badminton_analysis_v1_analysis_proto_rawDescGZIP() []byte {
	file_badminton_analysis_v1_analysis_proto_rawDescOnce.Do(func() {
		file_badminton_analysis_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badminton_analysis_v1_analysis_proto_rawDesc), len(file_badminton_analysis_v1_analysis_proto_rawDesc)))
	})
	return file_badminton_analysis_v1_analysis_proto_rawDescData
}

var file_badminton_analysis_v1_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_badminton_analysis_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_badminton_analysis_v1_analysis_proto_goTypes = []any{
	(Skill)(0),                          // 0: badminton.analysis.v1.Skill
	(Handedness)(0),                     // 1: badminton.analysis.v1.Handedness
	(*AnalyzeVideoHeader)(nil),          // 2: badminton.analysis.v1.AnalyzeVideoHeader
	(*AnalyzeVideoChunk)(nil),           // 3: badminton.analysis.v1.AnalyzeVideoChunk
	(*GradingDetail)(nil),               // 4: badminton.analysis.v1.GradingDetail
	(*GradingOutcome)(nil),              // 5: badminton.analysis.v1.GradingOutcome
	(*PhaseMarker)(nil),                 // 6: badminton.analysis.v1.PhaseMarker
	(*AlignmentSample)(nil),             // 7: badminton.analysis.v1.AlignmentSample
	(*CoachingCue)(nil),                 // 8: badminton.analysis.v1.CoachingCue
	(*StoredVideo)(nil),                 // 9: badminton.analysis.v1.StoredVideo
	(*ExpertMatch)(nil),                 // 10: badminton.analysis.v1.ExpertMatch
	(*DiagnosticValue)(nil),             // 11: badminton.analysis.v1.DiagnosticValue
	(*AnalyzeVideoResponse)(nil),        // 12: badminton.analysis.v1.AnalyzeVideoResponse
	(*RefreshPlaybackUrlsRequest)(nil),  // 13: badminton.analysis.v1.RefreshPlaybackUrlsRequest
	(*RefreshPlaybackUrlsResponse)(nil), // 14: badminton.analysis.v1.RefreshPlaybackUrlsResponse
	(*HealthRequest)(nil),               // 15: badminton.analysis.v1.HealthRequest
	(*HealthResponse)(nil),              // 16: badminton.analysis.v1.HealthResponse
}
var file_badminton_analysis_v1_analysis_proto_depIdxs = []int32{
	0,  // 0: badminton.analysis.v1.AnalyzeVideoHeader.skill:type_name -> badminton.analysis.v1.Skill
	1,  // 1: badminton.analysis.v1.AnalyzeVideoHeader.handedness:type_name -> badminton.analysis.v1.Handedness
	2,  // 2: badminton.analysis.v1.AnalyzeVideoChunk.header:type_name -> badminton.analysis.v1.AnalyzeVideoHeader
	4,  // 3: badminton.analysis.v1.GradingOutcome.grading_details:type_name -> badminton.analysis.v1.GradingDetail
	9,  // 4: badminton.analysis.v1.ExpertMatch.video:type_name -> badminton.analysis.v1.StoredVideo
	6,  // 5: badminton.analysis.v1.ExpertMatch.timeline:type_name -> badminton.analysis.v1.PhaseMarker
	7,  // 6: badminton.analysis.v1.ExpertMatch.alignment:type_name -> badminton.analysis.v1.AlignmentSample
	0,  // 7: badminton.analysis.v1.AnalyzeVideoResponse.skill:type_name -> badminton.analysis.v1.Skill
	1,  // 8: badminton.analysis.v1.AnalyzeVideoResponse.handedness:type_name -> badminton.analysis.v1.Handedness
	5,  // 9: badminton.analysis.v1.AnalyzeVideoResponse.grade:type_name -> badminton.analysis.v1.GradingOutcome
	9,  // 10: badminton.analysis.v1.AnalyzeVideoResponse.student_video:type_name -> badminton.analysis.v1.StoredVideo
	10, // 11: badminton.analysis.v1.AnalyzeVideoResponse.expert:type_name -> badminton.analysis.v1.ExpertMatch
	6,  // 12: badminton.analysis.v1.AnalyzeVideoResponse.timeline:type_name -> badminton.analysis.v1.PhaseMarker
	11, // 13: badminton.analysis.v1.AnalyzeVideoResponse.diagnostics:type_name -> badminton.analysis.v1.DiagnosticValue
	8,  // 14: badminton.analysis.v1.AnalyzeVideoResponse.coaching_cues:type_name -> badminton.analysis.v1.CoachingCue
	9,  // 15: badminton.analysis.v1.AnalyzeVideoResponse.skeleton_overlay_video:type_name -> badminton.analysis.v1.StoredVideo
	9,  // 16: badminton.analysis.v1.AnalyzeVideoResponse.feedback_video:type_name -> badminton.analysis.v1.StoredVideo
	9,  // 17: badminton.analysis.v1.RefreshPlaybackUrlsResponse.videos:type_name -> badminton.analysis.v1.StoredVideo
	0,  // 18: badminton.analysis.v1.HealthResponse.loaded_skills:type_name -> badminton.analysis.v1.Skill
	3,  // 19: badminton.analysis.v1.BadmintonAnalysis.AnalyzeVideo:input_type -> badminton.analysis.v1.AnalyzeVideoChunk
	13, // 20: badminton.analysis.v1.BadmintonAnalysis.RefreshPlaybackUrls:input_type -> badminton.analysis.v1.RefreshPlaybackUrlsRequest
	15, // 21: badminton.analysis.v1.BadmintonAnalysis.Health:input_type -> badminton.analysis.v1.HealthRequest
	12, // 22: badminton.analysis.v1.BadmintonAnalysis.AnalyzeVideo:output_type -> badminton.analysis.v1.AnalyzeVideoResponse
	14, // 23: badminton.analysis.v1.BadmintonAnalysis.RefreshPlaybackUrls:output_type -> badminton.analysis.v1.RefreshPlaybackUrlsResponse
	16, // 24: badminton.analysis.v1.BadmintonAnalysis.Health:output_type -> badminton.analysis.v1.HealthResponse
	22, // [22:25] is the sub-list for method output_type
	19, // [19:22] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_badminton_analysis_v1_analysis_proto_init() }
func file_badminton_analysis_v1_analysis_proto_init() {
	if File_badminton_analysis_v1_analysis_proto != nil {
		return
	}
	file_badminton_analysis_v1_analysis_proto_msgTypes[1].OneofWrappers = []any{
		(*AnalyzeVideoChunk_Header)(nil),
		(*AnalyzeVideoChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badminton_analysis_v1_analysis_proto_rawDesc), len(file_badminton_analysis_v1_analysis_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badminton_analysis_v1_analysis_proto_goTypes,
		DependencyIndexes: file_badminton_analysis_v1_analysis_proto_depIdxs,
		EnumInfos:         file_badminton_analysis_v1_analysis_proto_enumTypes,
		MessageInfos:      file_badminton_analysis_v1_analysis_proto_msgTypes,
	}.Build()
	File_badminton_analysis_v1_analysis_proto = out.File
	file_badminton_analysis_v1_analysis_proto_goTypes = nil
	file_badminton_analysis_v1_analysis_proto_depIdxs = nil
}
